POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Novo evento7", 
    "details": null,
    "maximumAttendees": 1
}

###

POST http://localhost:3333/events/21097992-d146-4a4a-937c-c8bf6d8e1a07/attendees
Content-Type: application/json

{
 "name": "Diego Fernandes",
 "email": "diego@rocketseat.com.br"
}

###

GET http://localhost:3333/events/21097992-d146-4a4a-937c-c8bf6d8e1a07

###

GET http://localhost:3333/attendees/1/badge

###

GET http://localhost:3333/attendees/2/check-in

###

GET http://localhost:3333/events/21097992-d146-4a4a-937c-c8bf6d8e1a07/attendees?query=Carlos
